### ISSUE TITLE
have you try to use the bert embedding instead of glove

### ISSUE THREAD

**Issue by zhouxincheng** [vijaydwivedi75/Beyond_word2vec#2]
is it a good idea to replace the glove vector using bert embedding? 
what I am doing right now is sentence alignment (monolingual), the difficulties are phrase to phrase alignment and word to phrase alignment. could your work be helpful to it?

**Comment by vijaydwivedi75** [comment]
The answer is Yes and the answer is No.

**1.** As you may understand, the reason I have used GloVe embedding was I needed a representation (_d-dim_) vector to input a 'single-word unit' to the Siamese LSTM, and the model learns phrase vectors only because we can leverage the PPDB dataset (and that is very generic). 

Coming to your question,(and following my paper's model approach) one should use BERT embedding in place of GloVe **if** the BERT embedding gives you **better representation of single-word units**. From [this discussion](https://www.reddit.com/r/MLQuestions/comments/atfr4u/bert_how_can_i_generate_word_embeddings_from_bert/), I follow not to use the BERT in the Siamese model  _because_ a comment here says:

> Moreover: BERT can do full-sentence representation. If your goal here is to do sentence similarity, you don't want to constrain BERT to token representations when it can do sentence representation.

BERT uses bidirectional contextual representation, but what we need in the Siamese model is an independent vector of a single-word unit.

**2.** However, if you use it, you should first figure out the way how you would input different vector representation, as per the context in the phrase, I can't say as to how we do it for now. 
You may read this [comment](https://www.reddit.com/r/MLQuestions/comments/atfr4u/bert_how_can_i_generate_word_embeddings_from_bert/eh35vkm/) and think.

Please share if you learn something on how to effectively do the sentence alignment.

**Comment by zhouxincheng** [comment]
Thank you for your reply and insightful view, that really helps and save my time.
I will let you know how to effectively do the alignment as soon as I figure it out.
